import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Head } from "next/document";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Meta httpEquiv="origin-trial" content={process.env.NEXT_PUBLIC_TRANSLATOR_TOKEN}/>
        <Meta httpEquiv="origin-trial" content={process.env.NEXT_PUBLIC_LANGUAGE_DECTECTOR_TOKEN}/>
        <Meta httpEquiv="origin-trial" content={process.env.NEXT_PUBLIC_SUMMARIZER_TOKEN}/>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
